config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"
  get "/favorite_spaces/:id", to: "home#show"
  get "/autocomplete", to: "search#show"
  post "/mailpayment/:id", to: "mailpayment#create", as: :mailpayment
  get "/paypal/:id", to: "mailpayment#edit", as: :check_payment
  post "/payment_update", to: "payment_booking#create", as: :payment_bookings
  get "/payment_booking/:id", to: "payment_booking#show", as: :payment_booking
  get "/payment_booking", to: "payment_booking#index", as: :thank_payment
  post "/like", to: "likes#create"
  delete "/unlike", to: "likes#destroy"
  get "/wishlist", to: "likes#wishlist"

  devise_for :admins, controllers: { sessions: "manager/sessions", passwords: "manager/passwords" }
  devise_for :members, controllers: { registrations: "registrations", sessions: "sessions",
                                      passwords: "passwords", confirmations: "confirmations" }
  get "/members/:member_id/rooms/:id/", to: "profiles#show", as: :show_profile
  get "/members/:id", to: "profiles#index", as: :index_profile

  resources :rooms do
    resources :prices
    resources :comments
  end

  resources :favorite_spaces, only: [:show]
  resources :search, only: :index
  resources :trends
  resources :bookings

  namespace :manager do
    root "members#index"

    resources :rooms do
      resources :prices
    end
    resources :favorite_spaces
    resources :rooms
    resources :admins
    resources :members
    resources :bookings
    resources :locations do
      resources :areas, except: %i[destroy edit update]
    end

    resources :areas
    resources :trends
    resources :utilities
  end
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  def new
    return redirect_to root_path, warning: t(".warning") unless check_params_exists?

    @booking = Booking.new
    @room = Room.find params[:room_id]
    @code_vouchers = @room.price.vouchers.map(&:code)
    return redirect_to root_path, warning: t(".warning") unless valid_date?

    check_valid_params
    check_valid_guest
    @night = ((@checkout - @checkin) / 60 / 60 / 24).to_i.abs
  end

  def create
    if params[:code_promotion].present?
      @voucher = Voucher.find_by code: params[:code_promotion]
      @booking = Booking.new booking_params.merge(voucher_id: @voucher.id)
      save_booking
    else
      @booking = Booking.new booking_params
      save_booking
    end
  end

  private

  def booking_params
    params.require(:booking).permit :checkin, :checkout, :room_id, :number_guest,
                                    :name_booking, :phone_booking, :email_booking, :name_booked, :phone_booked,
                                    :email_booked, :country_code, :trip_purpose, :request, :intend_time, :voucher_id
  end

  def check_params_exists?
    (params[:room_id] && params[:checkin] && params[:checkout] && params[:guest]).present?
  end

  def check_valid_params
    @checkin = DateTime.parse(params[:checkin]).localtime
    @checkout = DateTime.parse(params[:checkout]).localtime
    return redirect_to root_path, warning: t(".warning") if @checkin >= @checkout
  end

  def check_valid_guest
    if @room.guest < params[:guest].to_i.abs || params[:guest] !~ /\A[-+]?[0-9]+\z/
      redirect_to root_path, warning: t(".warning")
    end
  end

  def valid_date?
    date_format = "%d/%m/%Y"
    return true if DateTime.strptime(params[:checkin], date_format) && DateTime.strptime(params[:checkout], date_format)
  rescue ArgumentError
    false
  end

  def save_booking
    @booking.status = 0
    if @booking.save
      redirect_to thank_payment_path
    else
      flash[:danger] = t ".danger"
      redirect_to new_booking_path
    end
  end
end

app/controllers/manager/addresses_controller.rb
# frozen_string_literal: true

module Manager
  class AddressesController < BaseController
    before_action :load_address, only: %i[edit update destroy]

    def create
      @address = Address.new address_params
      if @address.save
        flash[:success] = t ".success"
      else
        flash.now[:danger] = t ".danger"
      end
      respond_to do |format|
        format.js
      end
    end

    def edit; end

    def update
      if @address.update name: params[:name]
        render json: { message: t(".success"), type: "success" }
      else
        render json: { message: t(".danger"), type: "error" }
      end
    end

    def destroy
      if @address.destroy
        flash[:success] = "ok"
      else
        flash[:danger] = "loi"
      end
      redirect_to edit_manager_area_path(@address.area_id)
    end

    private

    def address_params
      params.require(:address).permit :name, :area_id
    end

    def load_address
      @address = Address.find params[:id]
    end
  end
end

app/controllers/manager/admins_controller.rb
# frozen_string_literal: true

module Manager
  class AdminsController < BaseController
    before_action :check_default_admin
    before_action :all_admin, only: %i[index create update]
    before_action :load_admin, only: %i[edit update destroy]

    def index; end

    def new
      @admin = Admin.new
    end

    def create
      @admin = Admin.new admin_params
      if @admin.save
        flash.now[:success] = t "messages.success.admins.create"
      else
        flash.now[:danger] = t "messages.failed.admins.create"
      end
    end

    def update
      support_update @admin
      if @admin.changed?
        update_admin @admin
      else
        flash.now[:notice] = t("messages.notice.admins.not_edit", id: @admin.id)
      end
    end

    def destroy
      destroy_admin @admin
      redirect_to manager_admins_path
    end

    private

    def load_admin
      @admin = Admin.find(params[:id])
    end

    def admin_params
      params.require(:admin).permit :email, :name, :address,
                                    :password, :password_confirmation, :avatar
    end

    def update_admin(admin)
      if admin.save
        flash.now[:success] = t("messages.success.admins.update", id: admin.id)
      else
        flash.now[:danger] = t("messages.failed.admins.update", id: admin.id)
      end
    end

    def check_default_admin
      return if current_admin.flag?

      raise ActionController::RoutingError, params[:path]
    end

    def support_update(admin)
      admin.not_update_password = true if admin_params[:password].blank? && admin_params[:password_confirmation].blank?
      admin.assign_attributes admin_params
    end

    def destroy_admin(admin)
      if !admin.flag? && admin.destroy
        flash[:success] = t("messages.success.admins.delete", id: admin.id)
      else
        flash[:danger] = t("messages.failed.admins.delete", id: admin.id)
      end
    end

    def all_admin
      @admins = Admin.new_updated
    end
  end
end

app/controllers/manager/areas_controller.rb
# frozen_string_literal: true

module Manager
  class AreasController < BaseController
    before_action :load_area, only: %i[edit update destroy]

    def create
      @area = Area.new area_params
      if @area.save
        flash[:success] = t ".success"
      else
        flash[:danger] = t ".danger"
      end
      respond_to do |format|
        format.js
      end
    end

    def edit
      @address = @area.addresses.build
      @addresses = @area.addresses.newest.page(params[:page]).per Settings.address_per
    end

    def update
      if @area.update area_params
        flash[:success] = t ".success"
        redirect_to edit_manager_location_path(@area.location_id)
      else
        flash.now[:danger] = t ".danger"
        render :edit
      end
    end

    def destroy
      if @area.destroy
        flash[:success] = t ".success"
      else
        flash[:danger] = t ".danger"
      end
      redirect_to edit_manager_location_path(@area.location_id)
    end

    private

    def area_params
      params.require(:area).permit :name, :location_id
    end

    def load_area
      @area = Area.find params[:id]
    end
  end
end

app/controllers/manager/base_controller.rb
# frozen_string_literal: true

module Manager
  class BaseController < ApplicationController
    layout "manager"
    before_action :authenticate_admin!
  end
end

app/controllers/manager/bookings_controller.rb
# frozen_string_literal: true

module Manager
  class BookingsController < BaseController
    before_action :find_booking, only: %i[show edit update destroy]

    def index
      @bookings = Booking.includes(:room).newest.page(params[:page])
    end

    def show; end

    def edit; end

    def update
      if @booking.update(booking_params)
        redirect_to manager_booking_path, flash: { success: t(".success") }
      else
        render :edit
      end
    end

    def destroy
      redirect_to manager_bookings_path, flash: { success: t(".success") } if @booking.destroy
    end

    private

    def find_booking
      @booking = Booking.find(params[:id])
    end

    def booking_params
      params.require(:booking).permit(:checkin, :checkout, :number_guest,
                                      :name_booking, :phone_booking, :email_booking,
                                      :name_booked, :phone_booked, :email_booked,
                                      :trip_purpose, :country_code, :request)
    end
  end
end

app/controllers/manager/favorite_spaces_controller.rb
# frozen_string_literal: true

module Manager
  class FavoriteSpacesController < BaseController
    before_action :favorite_space, only: %i[edit update destroy]

    def index
      @favorite_spaces = FavoriteSpace.newest.page(params[:page]).per Settings.favorite_per
    end

    def new
      @favorite_space = FavoriteSpace.new
    end

    def create
      @favorite_space = FavoriteSpace.new(favorite_space_params)
      if @favorite_space.save
        redirect_to manager_favorite_spaces_path, flash: { success: t(".success") }
      else
        render :new
      end
    end

    def edit; end

    def update
      if @favorite_space.update_attributes(favorite_space_params)
        redirect_to manager_favorite_spaces_path, flash: { success: t(".success") }
      else
        render :edit
      end
    end

    def destroy
      redirect_to manager_favorite_spaces_path, flash: { success: t(".success") } if @favorite_space.destroy
    end

    private

    def favorite_space_params
      params.require(:favorite_space).permit(:name)
    end

    def favorite_space
      @favorite_space = FavoriteSpace.find(params[:id])
    end
  end
end

app/controllers/manager/locations_controller.rb
# frozen_string_literal: true

module Manager
  class LocationsController < BaseController
    before_action :load_location, only: %i[edit update destroy]

    def index
      @locations = Location.newest.page(params[:page]).per Settings.location_per
    end

    def new
      @location = Location.new
    end

    def edit
      @area = @location.areas.build
      @areas = @location.areas.newest.page(params[:page]).per Settings.location_per
    end

    def update
      if @location.update location_params
        redirect_to manager_locations_path, success: t(".success")
      else
        flash.now[:danger] = t ".danger"
        render :edit
      end
    end

    def create
      @location = Location.new location_params
      if @location.save
        redirect_to manager_locations_path, success: t(".success")
      else
        flash.now[:danger] = t ".danger"
        render :new
      end
    end

    def destroy
      if @location.destroy
        flash[:success] = t ".success"
      else
        flash.now[:danger] = t ".danger"
      end
      redirect_to manager_locations_path
    end

    private

    def location_params
      params.require(:location).permit :name, favorite_space_ids: []
    end

    def load_location
      @location = Location.find params[:id]
    end
  end
end

app/controllers/manager/members_controller.rb
# frozen_string_literal: true

module Manager
  class MembersController < BaseController
    before_action :all_member, only: %i[index create update]
    before_action :load_member, only: %i[edit update destroy]

    def index; end

    def new
      @member = Member.new
    end

    def create
      @member = Member.new member_params
      if @member.save
        flash.now[:success] = t "messages.success.members.create"
      else
        flash.now[:danger] = t "messages.failed.members.create"
      end
    end

    def update
      support_update @member
      if @member.changed?
        update_member @member
      else
        flash.now[:notice] = t("messages.notice.members.not_edit", id: @member.id)
      end
    end

    def destroy
      if @member.destroy
        flash[:success] = t("messages.success.members.delete", id: @member.id)
      else
        flash[:danger] = t("messages.failed.members.delete", id: @member.id)
      end
      redirect_to manager_members_path
    end

    private

    def member_params
      params.require(:member).permit :email, :name, :address,
                                     :password, :password_confirmation, :avatar
    end

    def load_member
      @member = Member.find(params[:id])
    end

    def update_member(member)
      if member.save
        flash.now[:success] = t("messages.success.members.update", id: member.id)
      else
        flash.now[:danger] = t("messages.failed.members.update", id: member.id)
      end
    end

    def support_update(member)
      member.not_update_password = true if member_params[:password]
                                           .blank? && member_params[:password_confirmation].blank?
      member.assign_attributes member_params
    end

    def all_member
      @members = Member.new_updated
    end
  end
end

app/controllers/manager/passwords_controller.rb
# frozen_string_literal: true

module Manager
  class PasswordsController < Devise::PasswordsController
    layout "sessions"
  end
end

app/controllers/manager/prices_controller.rb
# frozen_string_literal: true

module Manager
  class PricesController < BaseController
    before_action :load_price, only: %i[edit update]
    before_action :load_room, only: %i[edit new]

    def index
      @prices = Price.includes(:bills, :vouchers).newest
    end

    def edit
      @price.vouchers.build
    end

    def new
      @price = Price.new
      @price = @room.build_price
      @price.vouchers.build
    end

    def create
      @price = Price.new price_params
      if @price.save
        redirect_to manager_room_path(@price.room_id), flash: { success: t(".success") }
      else
        render :new
      end
    end

    def update
      if @price.update price_params
        redirect_to manager_room_path(@price.room_id), flash: { success: t(".success") }
      else
        render :edit
      end
    end

    private

    def price_params
      params.require(:price).permit :room_id, :cost, :cleaning_fee,
                                    vouchers_attributes: %i[id code sale date_off _destroy]
    end

    def load_price
      @price = Price.find(params[:id])
    end

    def load_room
      @room = Room.find params[:room_id]
    end
  end
end

app/controllers/manager/sessions_controller.rb
# frozen_string_literal: true

module Manager
  class SessionsController < Devise::SessionsController
    layout "sessions"
  end
end

app/controllers/manager/trends_controller.rb
# frozen_string_literal: true

module Manager
  class TrendsController < BaseController
    before_action :load_trend, only: %i[edit update destroy convert_status]

    def index
      @trends = Trend.newest.page(params[:pager]).per Settings.trend_per
    end

    def new
      @trend = Trend.new
    end

    def create
      @trend = Trend.new trend_params
      if @trend.save
        redirect_to manager_trends_path, success: t(".success")
      else
        flash.now[:danger] = t ".danger"
        render :new
      end
    end

    def edit; end

    def update
      if @trend.update trend_params
        redirect_to manager_trends_path, success: t(".success")
      else
        flash.now[:danger] = t ".danger"
        render :edit
      end
    end

    def destroy
      if @trend.destroy
        redirect_to manager_trends_path, success: t(".success")
      else
        redirect_to manager_trends_path, danger: t(".danger")
      end
    end

    private

    def trend_params
      params.require(:trend).permit :name, :description, :status, room_ids: []
    end

    def load_trend
      @trend = Trend.find params[:id]
    end
  end
end

app/helpers/managers_helper.rb
# frozen_string_literal: true

module ManagersHelper
  def select_of_types
    Room.type_rooms.keys.map { |t| [t.titleize, t] }
  end

  def build_location_for_rooms
    Location.sort_by_name.map { |l| [l.name, l.id] }
  end

  def build_area_to_location
    Area.sort_by_name.map { |a| [a.name, a.id] }
  end

  def build_favorite_space_for_rooms
    FavoriteSpace.sort_by_name.map { |fs| [fs.name, fs.id] }
  end

  def bill_vouchers(f)
    (f.price.cost - ((f.price.cost * f.voucher.sale) / 100)) + f.price.cleaning_fee
  end

  def select_favorite_space
    FavoriteSpace.all.map { |f| [f.name, f.id] }
  end

  def select_room
    Room.all.map { |r| [r.name, r.id] }
  end

  def select_status
    Trend.statuses.keys.map { |s| [s.titleize, s] }
  end

  def set_utilities
    Utility.sort_by_name
  end

  def like?(room)
    current_member.likes.find_by(room_id: room.id).present?
  end
end

app/views/manager/bookings/_booking.html.slim
tr
  td
    = link_to booking.room.name, manager_booking_path(booking)
  td
    = booking.checkin.strftime("%d/%m/%Y")
  td
    = booking.checkout.strftime("%d/%m/%Y")
  td
    = booking.status
  td
    - if booking.Pending?
      = link_to t(".send_email"), mailpayment_path(booking), method: :post, class: "btn btn-primary"
  td
    = link_to t(".destroy"), manager_booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"

app/views/manager/bookings/edit.html.slim
= form_for [:manager, @booking] do |booking|
  .container-fluid
    = render "shared/manager/error_messages", object: @booking
    div
      .title
        h3
          p = t(".information_booking")
      .number-guest
        .row
          .col-12
            p = t(".number_guest")
            p = booking.number_field :number_guest, class: "form-control"
      .date-booking
        .row
          .col-6
            div.checkin
              hr
              p = t(".checkin")
              p = booking.datetime_field :checkin, class: "form-control"
          .col-6
            div.checkout
              hr
              p = t(".checkout")
              p = booking.datetime_field :checkout, class: "form-control"
      hr
      .information-customer
        .title
          h3
            = t(".information_customer")
        .name
          p = t(".name_booking")
          p = booking.text_field :name_booking, class: "form-control"
        hr
        .phone-email
          .row
            .col-6
              p = t(".phone_booking")
              p = booking.text_field :phone_booking, class: "form-control", id: "phone-booking"
            .col-6
              p = t(".email_booking")
              p = booking.text_field :email_booking, class: "form-control"
        hr
        .country
          .row
            .col-12
              p = t(".country")
              p = booking.country_select(:country_code, { prompt: "Select one" }, class: "form-control")
        hr
        .description
          .row
            .col-12
              p = t(".request")
              p = booking.text_area :request, class: "form-control"
        hr
        .new-checkbox
          .row
            label.checkbox-booking
              p = t(".book_some")
              input#checkbox type="checkbox"
              span.checkmark
        .container#info-booked
          .name-booked
            .row
              .col-12
                p = t(".name_booked")
                p = booking.text_field :name_booked, class: "form-control"
          .phone-booked
            .row
              .col-6
                p = t(".phone_booked")
                p = booking.phone_field :phone_booked, class: "form-control"
              .col-6
                p = t(".email_booked")
                p = booking.email_field :email_booked, class: "form-control"
        = booking.submit t(".update"), class: "btn btn-primary"
        = link_to t(".back"), manager_bookings_path, class: "btn btn-secondary"

app/views/manager/bookings/index.html.slim
.row
  .col-md-12
    .card
      .card-header
        h4.card-title
          p = t(".manager_all_booking")
      .card-body
        table.table.table-hover.table-striped.text-center
          thead
            th = t(".name_room")
            th = t(".checkin")
            th = t(".checkout")
            th = t(".status")
            th colspan="2" = t(".action")
          tbody
            = render @bookings
= paginate @bookings, theme: "twitter-bootstrap-4", pagination_class: "pagination-sm"

app/views/manager/bookings/show.html.slim
.container-fluid
  form
    fieldset disabled="disabled"
      div
        .title
          h3
            p = t(".information_booking")
        hr
        .number-guest
          .row
            .col-12
              p = t(".number_guest")
              input#disabledTextInput.form-control placeholder=("#{ @booking.number_guest }") type="text"
        .date-booking
          .name-room
            p.font-weight-bold = t(".name_room")
            input#disabledTextInput.form-control placeholder=("#{ @booking.room.name }") type="text"
          .row
            .col-6
              div.checkin
                hr
                p.font-weight-bold = t(".checkin")
                input#disabledTextInput.form-control placeholder=("#{ @booking.checkin.strftime('%d - %m - %Y') }") type="text" /
            .col-6
              div.checkout
                hr
                p.font-weight-bold = t(".checkout")
                input#disabledTextInput.form-control placeholder=("#{ @booking.checkout.strftime('%d - %m - %Y') }") type="text"
        hr
        .information-customer
          .title
            h3
              = t(".information_customer")
          .name
            p.font-weight-bold = t(".name_booking")
            input#disabledTextInput.form-control placeholder=("#{ @booking.name_booking }") type="text"
          hr
          .phone-email
            .row
              .col-6
                p.font-weight-bold = t(".phone_booking")
                input#disabledTextInput.form-control placeholder=("#{ @booking.phone_booking }") type="text"
              .col-6
                p.font-weight-bold = t(".email_booking")
                input#disabledTextInput.form-control placeholder=("#{ @booking.email_booking }") type="text"
          hr
          .country
            .row
              .col-12
                p.font-weight-bold = t(".country")
                input#disabledTextInput.form-control placeholder=("#{ @booking.country_name }") type="text"
          hr
          .description
            .row
              .col-12
                p.font-weight-bold = t(".request")
                textarea#disabledTextInput.form-control placeholder=("#{ @booking.request }") type="text"
  hr
  .new-checkbox
    .row
      label.checkbox-booking
        p = t(".book_some")
        input#checkbox type="checkbox"
        span.checkmark
  form
    fieldset disabled="disabled"
      .container#info-booked
        .name-booked
          .row
            .col-12
              p = t(".name_booked")
              input#disabledTextInput.form-control placeholder=("#{ @booking.name_booked }") type="text"
        .phone-booked
          .row
            .col-6
              p = t(".phone_booked")
              input#disabledTextInput.form-control placeholder=("#{ @booking.phone_booked }") type="text"
            .col-6
              p = t(".email_booked")
              input#disabledTextInput.form-control placeholder=("#{ @booking.email_booked }") type="text"
    .action-booking
      = link_to t(".edit"), edit_manager_booking_path(@booking), class: "btn btn-primary"
      = link_to t(".back"), manager_bookings_path, class: "btn btn-secondary"