config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"
  get "/favorite_spaces/:id", to: "home#show"
  get "/autocomplete", to: "search#show"
  post "/mailpayment/:id", to: "mailpayment#create", as: :mailpayment
  get "/paypal/:id", to: "mailpayment#edit", as: :check_payment
  post "/payment_update", to: "payment_booking#create", as: :payment_bookings
  get "/payment_booking/:id", to: "payment_booking#show", as: :payment_booking
  get "/payment_booking", to: "payment_booking#index", as: :thank_payment
  post "/like", to: "likes#create"
  delete "/unlike", to: "likes#destroy"
  get "/wishlist", to: "likes#wishlist"

  devise_for :admins, controllers: { sessions: "manager/sessions", passwords: "manager/passwords" }
  devise_for :members, controllers: { registrations: "registrations", sessions: "sessions",
                                      passwords: "passwords", confirmations: "confirmations" }
  get "/members/:member_id/rooms/:id/", to: "profiles#show", as: :show_profile
  get "/members/:id", to: "profiles#index", as: :index_profile

  resources :rooms do
    resources :prices
    resources :comments
  end

  resources :favorite_spaces, only: [:show]
  resources :search, only: :index
  resources :trends
  resources :bookings

  namespace :manager do
    root "members#index"

    resources :rooms do
      resources :prices
    end
    resources :favorite_spaces
    resources :rooms
    resources :admins
    resources :members
    resources :bookings
    resources :locations do
      resources :areas, except: %i[destroy edit update]
    end

    resources :areas
    resources :trends
    resources :utilities
  end
end

app/models/trend.rb
class Trend < ApplicationRecord
end

app/controllers/manager/trends_controller.rb
# frozen_string_literal: true

module Manager
  class TrendsController < BaseController
    before_action :load_trend, only: %i[edit update destroy convert_status]

    def index
      @trends = Trend.newest.page(params[:pager]).per Settings.trend_per
    end

    def new
      @trend = Trend.new
    end

    def create
      @trend = Trend.new trend_params
      if @trend.save
        redirect_to manager_trends_path, success: t(".success")
      else
        flash.now[:danger] = t ".danger"
        render :new
      end
    end

    def edit; end

    def update
      if @trend.update trend_params
        redirect_to manager_trends_path, success: t(".success")
      else
        flash.now[:danger] = t ".danger"
        render :edit
      end
    end

    def destroy
      if @trend.destroy
        redirect_to manager_trends_path, success: t(".success")
      else
        redirect_to manager_trends_path, danger: t(".danger")
      end
    end

    private

    def trend_params
      params.require(:trend).permit :name, :description, :status, room_ids: []
    end

    def load_trend
      @trend = Trend.find params[:id]
    end
  end
end

app/controllers/trends_controller.rb
# frozen_string_literal: true

class TrendsController < ApplicationController
  def show
    @trend = Trend.find params[:id]
    @rooms = @trend.rooms.newest.page(params[:page]).per Settings.room_per
  end
end

app/views/trends/_trend.html.slim
.title-location
  h2.extra-bold.p--giant= link_to trend.name, trend_path(trend), class: "trend-title"
  p = trend.description
.row
  = render trend.rooms.includes(:trend_rooms, :room_images, :location, :price, :likes, :favorite_space).limit Settings.trend_limit

app/views/trends/show.html.slim
.container
  .info-rooms
    | #{t ".present"} #{@rooms.size} #{t ".allow"} #{link_to t(".booking"), "#"}
  .row
    - @rooms.each do |room|
      .card.col-md-3 style=("width: 18rem;")
        = link_to room_path(room), class: "room-image" do
          = image_tag load_limit_image(room), class: "card-img-top image-content"
        .card-body.promo-content
          .card-favorite-spaces = room.favorite_space.name
          .room-title = link_to room.name, "#", class: "trend-title"
          .room-details
            = room.guest
            |  #{t ".people"} #{room.bed_room} #{t ".bed_room"} #{room.bath_room} #{t ".bath_room"}
          .room-prices = number_to_currency(room.price_cost) if room.price.present?
          .room-locations
            = room.location_name
            | , #{room.address}
    .room_paginate
      = paginate @rooms, theme: "twitter-bootstrap-4", pagination_class: "pagination-sm"