config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"
  get "/favorite_spaces/:id", to: "home#show"
  get "/autocomplete", to: "search#show"
  post "/mailpayment/:id", to: "mailpayment#create", as: :mailpayment
  get "/paypal/:id", to: "mailpayment#edit", as: :check_payment
  post "/payment_update", to: "payment_booking#create", as: :payment_bookings
  get "/payment_booking/:id", to: "payment_booking#show", as: :payment_booking
  get "/payment_booking", to: "payment_booking#index", as: :thank_payment
  post "/like", to: "likes#create"
  delete "/unlike", to: "likes#destroy"
  get "/wishlist", to: "likes#wishlist"

  devise_for :admins, controllers: { sessions: "manager/sessions", passwords: "manager/passwords" }
  devise_for :members, controllers: { registrations: "registrations", sessions: "sessions",
                                      passwords: "passwords", confirmations: "confirmations" }
  get "/members/:member_id/rooms/:id/", to: "profiles#show", as: :show_profile
  get "/members/:id", to: "profiles#index", as: :index_profile

  resources :rooms do
    resources :prices
    resources :comments
  end

  resources :favorite_spaces, only: [:show]
  resources :search, only: :index
  resources :trends
  resources :bookings

  namespace :manager do
    root "members#index"

    resources :rooms do
      resources :prices
    end
    resources :favorite_spaces
    resources :rooms
    resources :admins
    resources :members
    resources :bookings
    resources :locations do
      resources :areas, except: %i[destroy edit update]
    end

    resources :areas
    resources :trends
    resources :utilities
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @favorite_spaces = FavoriteSpace.newest
    @trends = Trend.includes(:rooms, :trend_rooms).newest
  end

  def show
    @favorite_space = FavoriteSpace.find(params[:id])
    @room_favorite_space = @favorite_space.rooms
                                          .includes(:price, :location, :room_images).page(params[:page]).per Settings.room_per
  end
end

app/views/home/index.html.slim
= image_tag "nature.jpg", style: "width: 100%"
.banner-image
  h1 Hello
  p Welcome To Home Stay
.container.favorite-space
  .title-favorite-space
    h2.extra-bold.p--giant Start your holidays at BookingHomestay
    p At this holidays, we have a promotion up to 50 %
  #exampleSlider
    .MS-content
      - @favorite_spaces.each do |favorite_space|
        .item
          p
            = link_to favorite_space_path(favorite_space) do
              = image_tag "location_6"
            br
          .article_content
            .article_content.bold.title-content.text-center
              = link_to favorite_space.name, favorite_space_path(favorite_space)
    .MS-controls
      button.MS-left
        i.fa.fa-arrow-left
      button.MS-right
        i.fa.fa-arrow-right
  = render @trends

app/views/home/show.html.slim
.container
  .info-rooms
    | #{t ".present"} #{@favorite_space.rooms.size} #{t ".allow"} #{link_to t(".booking"), "#"}
  .row
    - @room_favorite_space.each do |room|
      .card.col-md-3 style=("width: 18rem;")
        = link_to room_path(room), class: "room-image" do
          = image_tag load_limit_image(room), class: "card-img-top image-content"
        .card-body.promo-content
          .card-favorite-spaces = room.favorite_space.name
          .room-title = link_to room.name, room_path(room), class: "trend-title"
          .room-details
            = room.guest
            |  #{t ".people"} #{room.bed_room} #{t ".bed_room"} #{room.bath_room} #{t ".bath_room"}
          .room-prices = number_to_currency(room.price_cost) if room.price.present?
          .room-locations
            = room.location_name
            | , #{room.address}
    .room_paginate
      = paginate @room_favorite_space, theme: "twitter-bootstrap-4", pagination_class: "pagination-sm"